filetype plugin indent on

set nu  " Line numbers on
"set nowrap  " Line wrapping off
" Formatting (some of these are for coding in C and C++)
set ts=2  " Tabs are 2 spaces
"set bs=2  " Backspace over everything in insert mode
"set shiftwidth=2  " Tabs under smart indent
"set autoindent
"set smarttab
  
" Visual
set showmatch  " Show matching brackets.
"set mat=5  " Bracket blinking.
 
syntax enable
set background=dark
colorscheme solarized

" set mouse=a
" map <ScrollWheelUp> <C-Y>
" map <ScrollWheelDown> <C-E>

" tell vim to use the system clipboard
set clipboard=unnamed
