# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="verbose"

# Customize to your needs...
PATH_PREFIX=$HOME/anaconda3/bin:$HOME/bin

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    # Oh my, zsh plugins
    plugins=(git)
else
    # Oh my, zsh plugins
    plugins=(git osx macports screen terminalapp)
fi

source $ZSH/oh-my-zsh.sh

# Allow things like "sudo !!" to work without the shell wanting confirmation
setopt no_hist_verify

# This has to be done after oh-my-zsh.sh is sourced
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    # GNU/Linux
    export LS_COLORS='di=1;34:ln=1;36:so=32:pi=33:ex=32:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43'
    PATH=$PATH_PREFIX:$PATH

    # this prevents 'git status' from being called when cd'ing into a git repo
    # that was just way too slow for shared filesystems.
    # the major draw back is that it suppresses the dirty repo flag, but that's
    # a small price to pay for it being usably fast.
    function git_prompt_info() {
      ref=$(git symbolic-ref HEAD 2> /dev/null) || return
      echo "$ZSH_THEME_GIT_PROMPT_PREFIX${ref#refs/heads/}$ZSH_THEME_GIT_PROMPT_SUFFIX"
    }

    # Get the most current Red Hat-provided devtools
    if [[ -f "/opt/rh/devtoolset-2/enable" ]]; then
        source /opt/rh/devtoolset-2/enable
    fi
else
    # NCBI C toolkit
    export NCBI_ROOT=$HOME/ncbi
    export NCBI_BIN=$NCBI_ROOT/bin
    export BLASTDB=$NCBI_ROOT/data
    export BLASTMAT=$NCBI_ROOT/data

    # Additional Mac settings for GNUplot, R and PyMOL
    export GNUTERM="aqua"
    export R_HOME=/Library/Frameworks/R.framework/Resources
    # alias pymol=/Applications/MacPyMOL.app/Contents/MacOS/MacPyMOL

    # BSD/macOS
    export LSCOLORS='ExGxcxdxcxegedabagacad'
    PATH=$PATH_PREFIX:$NCBI_BIN:/Library/TeX/texbin:/opt/local/bin:$PATH

    # test iTerm2 shell integration -- yes, you should be using iTerm2
    test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi

export PATH

if [[ -f $HOME/.rosetta3_rc ]]; then
    source $HOME/.rosetta3_rc
fi

alias ll='ls -hlt'

# Baker lab machines
alias digs="ssh digs"
alias jojo="ssh jojo"

